kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"bitnami.com/v1alpha1","kind":"SealedSecret","metadata":{"annotations":{"sealedsecrets.bitnami.com/cluster-wide":"true"},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"cluster-secrets"},"name":"i058650-docker-registry","namespace":"test-i058650"},"spec":{"encryptedData":{".dockercfg":"AgCWsw/J5xeh72dtQxXf3AbHfvQTtrE9s3kjiajNN4GjOicXINU9VnpPt1tMSjgoeQL+YOYEvHArDszp4dy5HmXSo4NxS5QDsX5TqIPL6A5Z2nKWSpsn1E7K1tlTyD4N0igaeMtqm4GAUZ2a0WC4/jz6FaN6hcdYUqHQfmCXzycXvJA8vhcKIxzeFy0795gxF3wn5zhKIh9JsFYS8t46687bGGtYUUKx6p+98BywKc4FdUBD4vY0zbwYP0kmrG3PnqPCZATIpXg3aFCq7Dt2qPWGq4ptLvUYUO/jlS+MYzcx3mZd6vuz/m+a+Zk9axuMol4W8F4Q+X5VIo+2Zw6xAXJleZk6c4VesaW+mlcZqOVyiZkVdXzqvMh9voGg43C2nUmE0Tlc71tPE5yreARnvqWNrjTOojMeceE2ewEyxvVNF5LcHjGNePwSzaNJVs/wccSVrYB3lx48Yqy6krXz2unHshW1hHLZ8HpSpK6F3nztSBLwL4viBxDE102A/ujmh9B7pUuCf2uA1pY/0/FDWVbF00g7qwDXfL9fMafNnYGqVfvFuq5Ys3l5QYMs+tORi9OMVSRuvV91mE3D4GtCWaR7YyDwDaCZN9lQljAdRueoTB07InJOqyKABa4nxAr/OlBJyWwvIHtokeQ5YLSpZmuiehU/VIJeK3JF+eBAh1r/q9d6oXUiBHHorUv8FTKbHaU01UykAr1eJLtyyktf7X/wmpUGTwvgPe1idEEHm7PmNCVjSVqMQAAEEb+PNhiRCN91C0ux2tqca/gqilgK11ViY5LEINGGcTwJfEnFTwnHvYzlJMYAVcXqvA=="},"template":{"metadata":{"annotations":{"replicator.v1.mittwald.de/replication-allowed":"true","replicator.v1.mittwald.de/replication-allowed-namespaces":".*","sealedsecrets.bitnami.com/cluster-wide":"true","type":"dockercfg"},"creationTimestamp":null,"name":"docker-registry","namespace":"test-i058650"},"type":"kubernetes.io/dockercfg"}}}
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    app.kubernetes.io/instance: cluster-secrets
  name: i058650-docker-registry
  namespace: test-i056850
spec:
  encryptedData:
    .dockercfg: >-
      AgCWsw/J5xeh72dtQxXf3AbHfvQTtrE9s3kjiajNN4GjOicXINU9VnpPt1tMSjgoeQL+YOYEvHArDszp4dy5HmXSo4NxS5QDsX5TqIPL6A5Z2nKWSpsn1E7K1tlTyD4N0igaeMtqm4GAUZ2a0WC4/jz6FaN6hcdYUqHQfmCXzycXvJA8vhcKIxzeFy0795gxF3wn5zhKIh9JsFYS8t46687bGGtYUUKx6p+98BywKc4FdUBD4vY0zbwYP0kmrG3PnqPCZATIpXg3aFCq7Dt2qPWGq4ptLvUYUO/jlS+MYzcx3mZd6vuz/m+a+Zk9axuMol4W8F4Q+X5VIo+2Zw6xAXJleZk6c4VesaW+mlcZqOVyiZkVdXzqvMh9voGg43C2nUmE0Tlc71tPE5yreARnvqWNrjTOojMeceE2ewEyxvVNF5LcHjGNePwSzaNJVs/wccSVrYB3lx48Yqy6krXz2unHshW1hHLZ8HpSpK6F3nztSBLwL4viBxDE102A/ujmh9B7pUuCf2uA1pY/0/FDWVbF00g7qwDXfL9fMafNnYGqVfvFuq5Ys3l5QYMs+tORi9OMVSRuvV91mE3D4GtCWaR7YyDwDaCZN9lQljAdRueoTB07InJOqyKABa4nxAr/OlBJyWwvIHtokeQ5YLSpZmuiehU/VIJeK3JF+eBAh1r/q9d6oXUiBHHorUv8FTKbHaU01UykAr1eJLtyyktf7X/wmpUGTwvgPe1idEEHm7PmNCVjSVqMQAAEEb+PNhiRCN91C0ux2tqca/gqilgK11ViY5LEINGGcTwJfEnFTwnHvYzlJMYAVcXqvA==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: 'true'
        replicator.v1.mittwald.de/replication-allowed-namespaces: .*
        sealedsecrets.bitnami.com/cluster-wide: 'true'
        type: dockercfg
      creationTimestamp: null
      name: i058650-docker-registry
      namespace: test-i056850
    type: kubernetes.io/dockercfg
